tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains

      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c

      # Ultimate Edition
      #sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-u

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
    